import type {
    Vendor,
    VendorAssignment,
    VendorContract,
    VendorCoverageAssignment,
    VendorDocument,
    VendorFeedback,
    VendorHistoryLog,
} from '@/lib/vendors/types';

export const VENDOR_CATEGORIES = ['Electrical', 'Plumbing', 'Civil', 'Security', 'Interior', 'HVAC', 'Cleaning', 'General'];
export const VENDOR_CITIES = ['Hyderabad', 'Bengaluru', 'Pune', 'Chennai', 'Mumbai'];

/** Properties / projects vendors can be assigned to (aligned with work-order seed data). */
export const VENDOR_PRIMARY_PROJECTS = ['Skyline Residency', 'Urban Flux Apartments', 'Summit Woods'] as const;

export const MOCK_VENDORS: Vendor[] = [
    {
        id: 'VND-1001',
        name: 'Prime Electrical Works',
        type: 'Contractor',
        categories: ['Electrical'],
        contactPerson: 'Rakesh N',
        phone: '+91 9876543210',
        email: 'rakesh@primeelectrical.com',
        city: 'Hyderabad',
        state: 'Telangana',
        country: 'India',
        status: 'Active',
        rating: 4.6,
        compliancePercent: 92,
        contractStatus: 'Active',
        docsComplete: 96,
        delays: 1,
        slaBreaches: 0,
        availability: 'High',
        primaryProject: 'Skyline Residency',
        createdAt: '2026-03-20',
    },
    {
        id: 'VND-1002',
        name: 'Metro Civil Solutions',
        type: 'Contractor',
        categories: ['Civil'],
        contactPerson: 'Ananya K',
        phone: '+91 9988776655',
        email: 'ananya@metrocivil.in',
        city: 'Pune',
        state: 'Maharashtra',
        country: 'India',
        status: 'Pending',
        rating: 3.9,
        compliancePercent: 71,
        contractStatus: 'Ending Soon',
        docsComplete: 68,
        delays: 4,
        slaBreaches: 2,
        availability: 'Medium',
        primaryProject: 'Urban Flux Apartments',
        createdAt: '2026-04-10',
    },
    {
        id: 'VND-1003',
        name: 'SafeGuard Security Services',
        type: 'Supplier',
        categories: ['Security'],
        contactPerson: 'Kiran P',
        phone: '+91 9123456789',
        email: 'kiran@safeguardsec.com',
        city: 'Bengaluru',
        state: 'Karnataka',
        country: 'India',
        status: 'Active',
        rating: 4.8,
        compliancePercent: 95,
        contractStatus: 'Active',
        docsComplete: 98,
        delays: 0,
        slaBreaches: 0,
        availability: 'High',
        primaryProject: 'Summit Woods',
        createdAt: '2025-12-02',
    },
    {
        id: 'VND-1004',
        name: 'Urban Interior Studio',
        type: 'Supplier',
        categories: ['Interior'],
        contactPerson: 'Megha T',
        phone: '+91 9345678123',
        email: 'megha@urbaninterior.co',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        status: 'Inactive',
        rating: 3.4,
        compliancePercent: 62,
        contractStatus: 'Expired',
        docsComplete: 54,
        delays: 6,
        slaBreaches: 4,
        availability: 'Low',
        primaryProject: 'Urban Flux Apartments',
        createdAt: '2025-09-14',
    },
    {
        id: 'VND-1005',
        name: 'BluePipe Plumbing Systems',
        type: 'Contractor',
        categories: ['Plumbing'],
        contactPerson: 'Suresh R',
        phone: '+91 9234567812',
        email: 'suresh@bluepipe.in',
        city: 'Mumbai',
        state: 'Maharashtra',
        country: 'India',
        status: 'Blacklisted',
        rating: 2.8,
        compliancePercent: 38,
        contractStatus: 'Expired',
        docsComplete: 40,
        delays: 9,
        slaBreaches: 6,
        availability: 'Low',
        primaryProject: 'Skyline Residency',
        createdAt: '2025-05-06',
    },
    {
        id: 'VND-1006',
        name: 'AquaFix Plumbing Co.',
        type: 'Contractor',
        categories: ['Plumbing'],
        contactPerson: 'Vikram Desai',
        phone: '+91 9012345678',
        email: 'dispatch@aquafix.in',
        city: 'Hyderabad',
        state: 'Telangana',
        country: 'India',
        status: 'Active',
        rating: 4.7,
        compliancePercent: 96,
        contractStatus: 'Active',
        docsComplete: 100,
        delays: 0,
        slaBreaches: 0,
        availability: 'High',
        primaryProject: 'Riverfront Tower',
        createdAt: '2025-08-12',
    },
    {
        id: 'VND-1007',
        name: 'CoolAir HVAC Specialists',
        type: 'Contractor',
        categories: ['HVAC'],
        contactPerson: 'Neha Sharma',
        phone: '+91 9098765432',
        email: 'ops@coolairhvac.com',
        city: 'Bengaluru',
        state: 'Karnataka',
        country: 'India',
        status: 'Active',
        rating: 4.5,
        compliancePercent: 91,
        contractStatus: 'Active',
        docsComplete: 94,
        delays: 1,
        slaBreaches: 0,
        availability: 'High',
        primaryProject: 'Skyline Courts',
        createdAt: '2025-10-03',
    },
    {
        id: 'VND-1008',
        name: 'SparkClean Facility Services',
        type: 'Contractor',
        categories: ['Cleaning'],
        contactPerson: 'Divya Menon',
        phone: '+91 9887766554',
        email: 'service@sparkclean.in',
        city: 'Pune',
        state: 'Maharashtra',
        country: 'India',
        status: 'Active',
        rating: 4.2,
        compliancePercent: 88,
        contractStatus: 'Active',
        docsComplete: 90,
        delays: 2,
        slaBreaches: 1,
        availability: 'Medium',
        primaryProject: 'Garden Plaza',
        createdAt: '2026-01-20',
    },
];

/** Default coverage used by auto assignment when no custom config is saved. */
export const MOCK_VENDOR_COVERAGE: VendorCoverageAssignment[] = [
    {
        vendorId: 'VND-1001',
        projectsCovered: ['Skyline Residency', 'Central Annex'],
        towersCovered: ['Skyline Residency', 'Central Annex'],
        categoriesCovered: ['Electrical'],
        serviceAreas: ['Hyderabad', 'Telangana'],
        preferredPriorityLevels: ['Medium', 'High', 'Critical'],
    },
    {
        vendorId: 'VND-1002',
        projectsCovered: ['Urban Flux Apartments', 'Marina Views'],
        towersCovered: ['Marina Views'],
        categoriesCovered: ['Civil'],
        serviceAreas: ['Pune', 'Maharashtra'],
        preferredPriorityLevels: ['Low', 'Medium', 'High'],
    },
    {
        vendorId: 'VND-1003',
        projectsCovered: ['Summit Woods', 'Central Annex'],
        towersCovered: ['Central Annex'],
        categoriesCovered: ['Security'],
        serviceAreas: ['Bengaluru', 'Karnataka'],
        preferredPriorityLevels: ['Medium', 'High', 'Critical'],
    },
    {
        vendorId: 'VND-1006',
        projectsCovered: ['Riverfront Tower', 'Skyline Residency'],
        towersCovered: ['Riverfront Tower', 'Skyline Residency'],
        categoriesCovered: ['Plumbing'],
        serviceAreas: ['Hyderabad', 'Mumbai', 'Maharashtra'],
        preferredPriorityLevels: ['High', 'Critical', 'Medium'],
    },
    {
        vendorId: 'VND-1007',
        projectsCovered: ['Skyline Courts', 'Skyline Residency'],
        towersCovered: ['Skyline Courts'],
        categoriesCovered: ['HVAC'],
        serviceAreas: ['Bengaluru', 'Karnataka'],
        preferredPriorityLevels: ['Critical', 'High', 'Medium'],
    },
    {
        vendorId: 'VND-1008',
        projectsCovered: ['Garden Plaza', 'Central Annex'],
        towersCovered: ['Garden Plaza'],
        categoriesCovered: ['Cleaning'],
        serviceAreas: ['Pune', 'Maharashtra'],
        preferredPriorityLevels: ['Low', 'Medium'],
    },
];

export const MOCK_VENDOR_DOCUMENTS: VendorDocument[] = [
    {
        id: 'DOC-1',
        vendorId: 'VND-1001',
        documentName: 'PAN Certificate',
        type: 'PAN',
        uploadedDate: '2026-03-20',
        issueDate: '2025-03-20',
        expiryDate: '2028-03-20',
        verificationStatus: 'Verified',
        verificationWorkflowStep: 'verified',
        verifiedBy: 'Admin',
        verifiedDate: '2026-03-21',
        approvalNotes: 'PAN matched with company registration.',
        fileName: 'prime-electrical-pan.pdf',
    },
    {
        id: 'DOC-2',
        vendorId: 'VND-1001',
        documentName: 'Trade License',
        type: 'License',
        uploadedDate: '2026-03-22',
        issueDate: '2026-01-15',
        expiryDate: '2026-08-01',
        verificationStatus: 'Pending Verification',
        verificationWorkflowStep: 'compliance_review',
        verifiedBy: '',
        fileName: 'trade-license-2026.pdf',
    },
    {
        id: 'DOC-3',
        vendorId: 'VND-1002',
        documentName: 'GST Certificate',
        type: 'GST',
        uploadedDate: '2026-04-10',
        issueDate: '2026-04-01',
        expiryDate: '2027-04-10',
        verificationStatus: 'Verified',
        verificationWorkflowStep: 'verified',
        verifiedBy: 'Admin',
        verifiedDate: '2026-04-11',
        approvalNotes: 'GST certificate validated.',
        fileName: 'metro-civil-gst.pdf',
    },
    {
        id: 'DOC-4',
        vendorId: 'VND-1003',
        documentName: 'Service Agreement',
        type: 'Agreement',
        uploadedDate: '2025-11-01',
        issueDate: '2025-11-01',
        expiryDate: '2025-12-31',
        verificationStatus: 'Expired',
        verifiedBy: 'Legal',
        fileName: 'safeguard-msa-2025.pdf',
        notes: 'Renewal requested.',
    },
    {
        id: 'DOC-5',
        vendorId: 'VND-1004',
        documentName: 'Insurance Policy',
        type: 'Insurance',
        uploadedDate: '2026-02-14',
        issueDate: '2026-02-01',
        expiryDate: '2027-02-01',
        verificationStatus: 'Rejected',
        verificationWorkflowStep: 'rejected',
        verifiedBy: '',
        fileName: 'urban-interior-insurance.pdf',
        notes: 'Coverage amount unclear — resubmit.',
        rejectionReason: 'GST number mismatch with registration records.',
    },
];

export const MOCK_VENDOR_CONTRACTS: VendorContract[] = [
    { id: 'CNT-1', vendorId: 'VND-1001', contractName: 'Tower A Electrical Contract', startDate: '2026-01-01', endDate: '2026-12-31', value: 3200000, status: 'Active', fileName: 'tower-a-electrical.pdf' },
    { id: 'CNT-2', vendorId: 'VND-1002', contractName: 'Civil Phase-2 Contract', startDate: '2025-06-01', endDate: '2026-05-15', value: 4100000, status: 'Ending Soon', fileName: 'civil-phase2.pdf' },
    { id: 'CNT-3', vendorId: 'VND-1005', contractName: 'Plumbing Maintenance', startDate: '2024-04-01', endDate: '2025-03-31', value: 1200000, status: 'Expired', fileName: 'plumbing-maintenance.pdf' },
];

export const MOCK_VENDOR_ASSIGNMENTS: VendorAssignment[] = [
    { id: 'ASG-1', vendorId: 'VND-1001', workOrderId: 'WO-9001', taskTitle: 'Basement cable routing', assignedDate: '2026-04-01', priority: 'High', dueDate: '2026-04-30', status: 'In Progress', progress: 72 },
    { id: 'ASG-2', vendorId: 'VND-1002', workOrderId: 'WO-9002', taskTitle: 'Compound wall repair', assignedDate: '2026-04-10', priority: 'Medium', dueDate: '2026-05-20', status: 'Pending', progress: 20 },
    { id: 'ASG-3', vendorId: 'VND-1003', workOrderId: 'WO-9003', taskTitle: 'Security camera setup', assignedDate: '2026-03-15', priority: 'Critical', dueDate: '2026-04-25', status: 'Delayed', progress: 58 },
    { id: 'ASG-4', vendorId: 'VND-1001', workOrderId: 'WO-9004', taskTitle: 'Fire alarm audit', assignedDate: '2026-02-01', priority: 'High', dueDate: '2026-03-10', status: 'Completed', progress: 100 },
    { id: 'ASG-5', vendorId: 'VND-1001', workOrderId: 'WO-9005', taskTitle: 'Panel upgrade L2', assignedDate: '2026-01-12', priority: 'Medium', dueDate: '2026-02-01', status: 'Completed', progress: 100 },
    { id: 'ASG-6', vendorId: 'VND-1002', workOrderId: 'WO-9006', taskTitle: 'Retaining wall pour', assignedDate: '2026-03-01', priority: 'High', dueDate: '2026-03-28', status: 'Completed', progress: 100 },
    { id: 'ASG-7', vendorId: 'VND-1003', workOrderId: 'WO-9007', taskTitle: 'Lobby access control', assignedDate: '2026-02-20', priority: 'High', dueDate: '2026-03-15', status: 'Completed', progress: 100 },
    { id: 'ASG-8', vendorId: 'VND-1004', workOrderId: 'WO-9008', taskTitle: 'Show flat fit-out', assignedDate: '2025-11-10', priority: 'Low', dueDate: '2025-12-20', status: 'Completed', progress: 100 },
    { id: 'ASG-9', vendorId: 'VND-1005', workOrderId: 'WO-9009', taskTitle: 'Stack riser flush', assignedDate: '2025-08-01', priority: 'Medium', dueDate: '2025-09-10', status: 'Completed', progress: 100 },
    { id: 'ASG-10', vendorId: 'VND-1001', workOrderId: 'WO-9010', taskTitle: 'Generator cabling', assignedDate: '2025-12-05', priority: 'Critical', dueDate: '2026-01-10', status: 'Completed', progress: 100 },
    { id: 'ASG-11', vendorId: 'VND-1002', workOrderId: 'WO-9011', taskTitle: 'Ramp waterproofing', assignedDate: '2026-04-02', priority: 'Medium', dueDate: '2026-04-18', status: 'In Progress', progress: 44 },
    { id: 'ASG-12', vendorId: 'VND-1004', workOrderId: 'WO-9012', taskTitle: 'Ceiling grid rework', assignedDate: '2026-03-22', priority: 'High', dueDate: '2026-04-05', status: 'Delayed', progress: 62 },
];

export const MOCK_VENDOR_FEEDBACK: VendorFeedback[] = [
    { id: 'FDB-1', vendorId: 'VND-1001', date: '2026-04-11', reviewer: 'Project Manager', rating: 5, comment: 'Excellent execution and timely closure.' },
    { id: 'FDB-2', vendorId: 'VND-1001', date: '2026-03-20', reviewer: 'Site Lead', rating: 4, comment: 'Good quality, minor delays in material updates.' },
    { id: 'FDB-3', vendorId: 'VND-1002', date: '2026-04-12', reviewer: 'Operations', rating: 3, comment: 'Documentation pending verification.' },
];

export const MOCK_VENDOR_HISTORY: VendorHistoryLog[] = [
    // VND-1001 — Prime Electrical Works
    { id: 'HIS-1', vendorId: 'VND-1001', dateTime: '2026-04-12 10:35', user: 'Amit', action: 'Edited phone number', module: 'Vendor Profile', oldValue: '+91 9876500000', newValue: '+91 9876543210' },
    { id: 'HIS-2', vendorId: 'VND-1001', dateTime: '2026-04-10 16:22', user: 'Raj', action: 'Uploaded GST certificate', module: 'Documents', oldValue: 'Missing', newValue: 'Uploaded' },
    { id: 'HIS-4', vendorId: 'VND-1001', dateTime: '2026-04-07 09:10', user: 'Priya Nair', action: 'Updated categories', module: 'Vendor Profile', oldValue: 'Electrical', newValue: 'Electrical, Low voltage' },
    { id: 'HIS-5', vendorId: 'VND-1001', dateTime: '2026-04-02 14:00', user: 'System', action: 'Contract renewed', module: 'Contracts', oldValue: 'CNT-1 end 2026-05', newValue: 'Extended 12 months' },
    { id: 'HIS-6', vendorId: 'VND-1001', dateTime: '2026-03-22 11:20', user: 'Amit', action: 'Bank details verified', module: 'Finance', oldValue: 'Pending', newValue: 'Verified' },
    // VND-1002 — Metro Civil Solutions
    { id: 'HIS-3', vendorId: 'VND-1002', dateTime: '2026-04-09 11:42', user: 'Admin', action: 'Changed status', module: 'Vendor List', oldValue: 'Active', newValue: 'Inactive' },
    { id: 'HIS-7', vendorId: 'VND-1002', dateTime: '2026-04-06 15:30', user: 'Rajesh Kumar', action: 'Added site contact', module: 'Vendor Profile', oldValue: '—', newValue: 'Ananya K (site)' },
    { id: 'HIS-8', vendorId: 'VND-1002', dateTime: '2026-03-30 10:05', user: 'Admin', action: 'Uploaded MSME certificate', module: 'Documents', oldValue: 'Not uploaded', newValue: 'msme-metro.pdf' },
    { id: 'HIS-9', vendorId: 'VND-1002', dateTime: '2026-03-18 09:00', user: 'Ops', action: 'Onboarding checklist started', module: 'Vendor List', oldValue: 'Draft', newValue: 'In review' },
    // VND-1003 — SafeGuard Security
    { id: 'HIS-10', vendorId: 'VND-1003', dateTime: '2026-04-01 12:45', user: 'Kavita Legal', action: 'Background check cleared', module: 'Compliance', oldValue: 'In progress', newValue: 'Cleared' },
    { id: 'HIS-11', vendorId: 'VND-1003', dateTime: '2026-03-25 16:10', user: 'Priya Nair', action: 'Edited email', module: 'Vendor Profile', oldValue: 'kiran@safeguard.co', newValue: 'kiran@safeguardsec.com' },
    { id: 'HIS-12', vendorId: 'VND-1003', dateTime: '2026-03-10 08:30', user: 'Admin', action: 'Vendor created', module: 'Vendor List', oldValue: '—', newValue: 'SafeGuard Security Services' },
    // VND-1004 — Urban Interior Studio
    { id: 'HIS-13', vendorId: 'VND-1004', dateTime: '2026-02-14 13:00', user: 'Admin', action: 'Marked inactive', module: 'Vendor List', oldValue: 'Active', newValue: 'Inactive' },
    { id: 'HIS-14', vendorId: 'VND-1004', dateTime: '2026-01-20 10:15', user: 'Raj', action: 'Contract expired notice', module: 'Contracts', oldValue: 'Active', newValue: 'Expired' },
    // VND-1005 — BluePipe Plumbing
    { id: 'HIS-15', vendorId: 'VND-1005', dateTime: '2026-03-01 09:00', user: 'Admin', action: 'Vendor blacklisted', module: 'Vendor List', oldValue: 'Inactive', newValue: 'Blacklisted' },
    { id: 'HIS-16', vendorId: 'VND-1005', dateTime: '2026-02-10 14:30', user: 'Legal', action: 'Dispute flag raised', module: 'Compliance', oldValue: 'None', newValue: 'Open dispute #DP-882' },
];

export function getVendorById(id: string): Vendor | undefined {
    return MOCK_VENDORS.find((vendor) => vendor.id === id);
}
