'use client';

import React from 'react';
import Link from 'next/link';
import {
    LuArrowRight,
    LuCalendar,
    LuListChecks,
    LuPhone,
    LuTrendingUp,
    LuUserPlus,
    LuUsers,
} from 'react-icons/lu';
import type {
    AutoGeneratedTask,
    FollowUpRiskCommandRow,
    LeadLeakageMonitorSummary,
    LikelyClosureRow,
    RevenueAtRiskRow,
    SalesRepPerformance,
    SiteVisitConversionStats,
    TodaysRevenueAction,
} from '@/lib/leadsIntelligenceDecisionHelpers';
import { actionPillClass, formatRevenueLakhs } from '@/lib/leadsIntelligenceHelpers';
import type { LeadsIntelSecondaryMetrics } from '@/lib/leadsIntelligenceHelpers';
import { leadProfileHref } from '@/lib/leadRoutes';
import { LeadsIntelAiPanel, LeadsIntelAiSectionHeader, MetricPill } from '@/components/leads-intelligence/leadsIntelligenceUi';
import { cn } from '@/lib/utils';

const th = 'px-4 py-2.5 text-left text-[10px] font-bold uppercase tracking-wider text-slate-500';
const td = 'px-4 py-3 text-sm text-slate-800';

export function TodaysRevenueActions({ actions }: { actions: TodaysRevenueAction[] }) {
    return (
        <LeadsIntelAiPanel variant="violet" aria-label="Today's revenue actions">
            <LeadsIntelAiSectionHeader
                title="Today's Revenue Actions"
                subtitle="Take these steps today to protect and grow pipeline revenue."
                variant="violet"
                badge="Do today"
            />
            {actions.length === 0 ? (
                <p className="px-4 py-8 text-center text-sm text-slate-500">No actions for this view.</p>
            ) : (
                <ul className="divide-y divide-slate-100">
                    {actions.map((item) => (
                        <li key={item.id} className="flex flex-col gap-2 px-4 py-3.5 sm:flex-row sm:items-center sm:justify-between">
                            <div className="min-w-0">
                                <Link href={leadProfileHref(item.lead.leadSlug)} className="text-sm font-bold text-slate-900 hover:text-violet-700 hover:underline">
                                    {item.headline}
                                </Link>
                                <p className="mt-0.5 text-xs text-slate-600">
                                    <span className={cn('inline-flex rounded-full border px-2 py-0.5 font-semibold', actionPillClass(item.action))}>
                                        {item.action}
                                    </span>
                                    <span className="mx-2 text-slate-300">·</span>
                                    Impact: {item.businessImpact}
                                </p>
                                {item.dealContextHint ? (
                                    <p className="mt-1 text-xs font-medium text-violet-800">
                                        Deal data: {item.dealContextHint}
                                    </p>
                                ) : null}
                            </div>
                            <span className="shrink-0 text-sm font-bold text-emerald-800">{formatRevenueLakhs(item.potentialRevenueLakhs)}</span>
                        </li>
                    ))}
                </ul>
            )}
        </LeadsIntelAiPanel>
    );
}

export function RevenueAtRiskSection({ rows }: { rows: RevenueAtRiskRow[] }) {
    return (
        <LeadsIntelAiPanel variant="rose" aria-label="Revenue at risk">
            <LeadsIntelAiSectionHeader
                title="Revenue At Risk"
                subtitle="Leads that may be lost — recover revenue before it leaks."
                variant="rose"
            />
            <div className="overflow-x-auto">
                <table className="min-w-full border-collapse">
                    <thead>
                        <tr className="border-b border-rose-100/80 bg-rose-50/50">
                            <th className={th}>Lead</th>
                            <th className={th}>Potential revenue</th>
                            <th className={th}>Risk reason</th>
                            <th className={th}>Last follow-up</th>
                            <th className={th}>Recommended action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {rows.length === 0 ? (
                            <tr>
                                <td colSpan={5} className="px-4 py-8 text-center text-sm text-slate-500">
                                    No revenue at risk in this view.
                                </td>
                            </tr>
                        ) : (
                            rows.map((row, i) => (
                                <tr key={row.lead.id} className={cn('border-b border-slate-100', i % 2 === 1 && 'bg-slate-50/50')}>
                                    <td className={td}>
                                        <Link href={leadProfileHref(row.lead.leadSlug)} className="font-semibold hover:underline">
                                            {row.lead.name}
                                        </Link>
                                    </td>
                                    <td className={cn(td, 'font-bold text-rose-800')}>{formatRevenueLakhs(row.potentialRevenueLakhs)}</td>
                                    <td className={td}>{row.riskReason}</td>
                                    <td className={cn(td, 'text-slate-600')}>{row.lastFollowUp}</td>
                                    <td className={td}>
                                        <span className={cn('rounded-full border px-2 py-0.5 text-xs font-semibold', actionPillClass(row.recommendedAction))}>
                                            {row.recommendedAction}
                                        </span>
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
        </LeadsIntelAiPanel>
    );
}

export function LikelyClosuresSection({ rows }: { rows: LikelyClosureRow[] }) {
    return (
        <LeadsIntelAiPanel variant="emerald" aria-label="Likely closures">
            <LeadsIntelAiSectionHeader
                title="Hot Leads To Close This Week"
                subtitle="Highest booking probability — focus sales effort here first."
                variant="emerald"
            />
            <div className="overflow-x-auto">
                <table className="min-w-full border-collapse">
                    <thead>
                        <tr className="border-b border-emerald-100/80 bg-emerald-50/50">
                            <th className={th}>Lead</th>
                            <th className={cn(th, 'text-right')}>Conversion</th>
                            <th className={th}>Potential revenue</th>
                            <th className={th}>Expected close</th>
                        </tr>
                    </thead>
                    <tbody>
                        {rows.length === 0 ? (
                            <tr>
                                <td colSpan={4} className="px-4 py-8 text-center text-sm text-slate-500">
                                    No likely closures in this view.
                                </td>
                            </tr>
                        ) : (
                            rows.map((row, i) => (
                                <tr key={row.lead.id} className={cn('border-b border-slate-100', i % 2 === 1 && 'bg-slate-50/50')}>
                                    <td className={td}>
                                        <Link href={leadProfileHref(row.lead.leadSlug)} className="font-semibold hover:underline">
                                            {row.lead.name}
                                        </Link>
                                    </td>
                                    <td className={cn(td, 'text-right font-bold text-emerald-700')}>{row.conversionProbability}%</td>
                                    <td className={cn(td, 'font-semibold text-indigo-800')}>{formatRevenueLakhs(row.potentialRevenueLakhs)}</td>
                                    <td className={td}>
                                        <span className="inline-flex items-center gap-1 text-slate-700">
                                            <LuCalendar size={14} aria-hidden />
                                            {row.expectedCloseDate}
                                        </span>
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
        </LeadsIntelAiPanel>
    );
}

export function SalesTeamPerformanceSection({ reps }: { reps: SalesRepPerformance[] }) {
    return (
        <LeadsIntelAiPanel variant="indigo" aria-label="Sales team performance">
            <LeadsIntelAiSectionHeader
                title="Team Performance"
                subtitle="Who needs coaching — conversion and follow-up compliance at a glance."
                variant="indigo"
                badge="Manager view"
            />
            <div className="overflow-x-auto p-1">
                <table className="min-w-full border-collapse">
                    <thead>
                        <tr className="border-b border-indigo-100/80 bg-indigo-50/50">
                            <th className={th}>Salesperson</th>
                            <th className={cn(th, 'text-right')}>Assigned leads</th>
                            <th className={cn(th, 'text-right')}>Conversion</th>
                            <th className={th}>Revenue closed</th>
                            <th className={cn(th, 'text-right')}>Follow-up compliance</th>
                        </tr>
                    </thead>
                    <tbody>
                        {reps.length === 0 ? (
                            <tr>
                                <td colSpan={5} className="px-4 py-8 text-center text-sm text-slate-500">
                                    No assignee data in this view.
                                </td>
                            </tr>
                        ) : (
                            reps.map((rep, i) => (
                                <tr key={rep.name} className={cn('border-b border-slate-100', i % 2 === 1 && 'bg-slate-50/50')}>
                                    <td className={cn(td, 'font-semibold')}>
                                        <span className="inline-flex items-center gap-2">
                                            <LuUsers size={14} className="text-indigo-600" aria-hidden />
                                            {rep.name}
                                        </span>
                                    </td>
                                    <td className={cn(td, 'text-right tabular-nums')}>{rep.assignedLeads}</td>
                                    <td className={cn(td, 'text-right font-bold text-emerald-700')}>{rep.conversionPct}%</td>
                                    <td className={cn(td, 'font-semibold text-indigo-800')}>{formatRevenueLakhs(rep.revenueClosedLakhs)}</td>
                                    <td className={cn(td, 'text-right tabular-nums')}>{rep.followUpCompliancePct}%</td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
        </LeadsIntelAiPanel>
    );
}

export function FollowUpRiskCommandCenter({
    rows,
    onQuickCall,
    onQuickVisit,
    onQuickAssign,
}: {
    rows: FollowUpRiskCommandRow[];
    onQuickCall?: (slug: string, name: string) => void;
    onQuickVisit?: (name: string) => void;
    onQuickAssign?: (name: string) => void;
}) {
    return (
        <LeadsIntelAiPanel variant="rose" aria-label="Follow-up risk command center">
            <LeadsIntelAiSectionHeader
                title="Follow-Up Risk Command Center"
                subtitle="Overdue, missed, and inactive leads — quick actions to stop leakage."
                variant="rose"
            />
            <div className="overflow-x-auto">
                <table className="min-w-full border-collapse">
                    <thead>
                        <tr className="border-b border-rose-100/80 bg-rose-50/50">
                            <th className={th}>Lead</th>
                            <th className={th}>Issue</th>
                            <th className={th}>At stake</th>
                            <th className={th}>Action</th>
                            <th className={th}>Quick action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {rows.length === 0 ? (
                            <tr>
                                <td colSpan={5} className="px-4 py-8 text-center text-sm text-slate-500">
                                    No follow-up risks in this view.
                                </td>
                            </tr>
                        ) : (
                            rows.map((row, i) => (
                                <tr key={row.lead.id} className={cn('border-b border-slate-100', i % 2 === 1 && 'bg-slate-50/50')}>
                                    <td className={td}>
                                        <Link href={leadProfileHref(row.lead.leadSlug)} className="font-semibold hover:underline">
                                            {row.lead.name}
                                        </Link>
                                    </td>
                                    <td className={td}>{row.issueLabel}</td>
                                    <td className={cn(td, 'font-bold text-rose-800')}>{formatRevenueLakhs(row.potentialRevenueLakhs)}</td>
                                    <td className={td}>
                                        <span className={cn('rounded-full border px-2 py-0.5 text-xs font-semibold', actionPillClass(row.recommendedAction))}>
                                            {row.recommendedAction}
                                        </span>
                                    </td>
                                    <td className={td}>
                                        <div className="flex flex-wrap gap-1">
                                            {row.quickAction === 'Call Now' ? (
                                                <button
                                                    type="button"
                                                    className="inline-flex items-center gap-1 rounded-lg border border-sky-200 bg-sky-50 px-2 py-1 text-xs font-semibold text-sky-800 hover:bg-sky-100"
                                                    onClick={() => onQuickCall?.(row.lead.leadSlug, row.lead.name)}
                                                >
                                                    <LuPhone size={12} aria-hidden />
                                                    Call Now
                                                </button>
                                            ) : row.quickAction === 'Schedule Visit' ? (
                                                <button
                                                    type="button"
                                                    className="inline-flex items-center gap-1 rounded-lg border border-emerald-200 bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-800 hover:bg-emerald-100"
                                                    onClick={() => onQuickVisit?.(row.lead.name)}
                                                >
                                                    Schedule Visit
                                                </button>
                                            ) : (
                                                <button
                                                    type="button"
                                                    className="inline-flex items-center gap-1 rounded-lg border border-violet-200 bg-violet-50 px-2 py-1 text-xs font-semibold text-violet-800 hover:bg-violet-100"
                                                    onClick={() => onQuickAssign?.(row.lead.name)}
                                                >
                                                    <LuUserPlus size={12} aria-hidden />
                                                    Assign Owner
                                                </button>
                                            )}
                                        </div>
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
        </LeadsIntelAiPanel>
    );
}

export function LeadLeakageMonitorCard({ summary }: { summary: LeadLeakageMonitorSummary }) {
    return (
        <LeadsIntelAiPanel variant="rose" aria-label="Lead leakage monitor">
            <LeadsIntelAiSectionHeader title="Lead Leakage Monitor" subtitle="Management visibility on revenue walking out." variant="rose" />
            <div className="grid grid-cols-1 gap-3 p-4 sm:grid-cols-3">
                <MetricPill label="Total at-risk leads" value={String(summary.totalAtRisk)} tone="rose" />
                <MetricPill label="Potential revenue loss" value={formatRevenueLakhs(summary.potentialRevenueLossLakhs)} tone="rose" />
                <MetricPill label="Urgent recoveries" value={String(summary.urgentRecoveries)} tone="violet" />
            </div>
        </LeadsIntelAiPanel>
    );
}

export function SiteVisitConversionSection({ stats }: { stats: SiteVisitConversionStats }) {
    return (
        <LeadsIntelAiPanel variant="cyan" aria-label="Site visit conversion">
            <LeadsIntelAiSectionHeader
                title="Site Visit Conversion Analytics"
                subtitle="Real estate effectiveness — visits that become bookings."
                variant="cyan"
            />
            <div className="flex flex-col items-stretch gap-3 p-4 sm:flex-row sm:items-center">
                <div className="flex flex-1 flex-col items-center rounded-xl border border-cyan-100 bg-cyan-50/50 px-4 py-3">
                    <p className="text-[10px] font-bold uppercase text-cyan-800">Site visits</p>
                    <p className="text-3xl font-bold text-cyan-950">{stats.siteVisits}</p>
                </div>
                <LuArrowRight className="mx-auto hidden h-5 w-5 text-slate-300 sm:block" aria-hidden />
                <div className="flex flex-1 flex-col items-center rounded-xl border border-emerald-100 bg-emerald-50/50 px-4 py-3">
                    <p className="text-[10px] font-bold uppercase text-emerald-800">Bookings</p>
                    <p className="text-3xl font-bold text-emerald-950">{stats.bookings}</p>
                </div>
                <div className="flex flex-1 flex-col items-center rounded-xl border border-violet-100 bg-violet-50/50 px-4 py-3">
                    <p className="text-[10px] font-bold uppercase text-violet-800">Conversion</p>
                    <p className="flex items-center gap-1 text-3xl font-bold text-violet-950">
                        <LuTrendingUp size={22} aria-hidden />
                        {stats.conversionPct}%
                    </p>
                </div>
            </div>
        </LeadsIntelAiPanel>
    );
}

export function AutoTaskPlanner({ tasks }: { tasks: AutoGeneratedTask[] }) {
    const priorityTone = {
        High: 'border-rose-200 bg-rose-50 text-rose-800',
        Medium: 'border-amber-200 bg-amber-50 text-amber-800',
        Low: 'border-slate-200 bg-slate-50 text-slate-700',
    };
    return (
        <LeadsIntelAiPanel variant="amber" aria-label="AI task planner">
            <LeadsIntelAiSectionHeader
                title="AI Task Planner"
                subtitle="Auto-generated calls, visits, follow-ups, offers, and escalations."
                variant="amber"
                badge="Less CRM work"
            />
            {tasks.length === 0 ? (
                <p className="px-4 py-8 text-center text-sm text-slate-500">No tasks generated for this view.</p>
            ) : (
                <ul className="divide-y divide-slate-100 px-2">
                    {tasks.map((t) => (
                        <li key={t.id} className="flex flex-wrap items-center justify-between gap-2 py-3">
                            <div>
                                <Link href={leadProfileHref(t.leadSlug)} className="text-sm font-semibold hover:underline">
                                    {t.leadName}
                                </Link>
                                <p className="flex items-center gap-1 text-xs text-slate-600">
                                    <LuListChecks size={12} aria-hidden />
                                    {t.task} · {t.dueLabel}
                                </p>
                            </div>
                            <span className={cn('rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase', priorityTone[t.priority])}>
                                {t.priority}
                            </span>
                        </li>
                    ))}
                </ul>
            )}
        </LeadsIntelAiPanel>
    );
}

export function SecondaryAnalyticsStrip({ metrics }: { metrics: LeadsIntelSecondaryMetrics }) {
    return (
        <details className="rounded-xl border border-slate-200/80 bg-slate-50/50 px-4 py-3">
            <summary className="cursor-pointer text-xs font-semibold uppercase tracking-wide text-slate-500">
                Supporting metrics (lead score, engagement, campaigns)
            </summary>
            <div className="mt-3 grid grid-cols-3 gap-3">
                <div className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-center">
                    <p className="text-[10px] font-bold uppercase text-slate-400">Avg lead score</p>
                    <p className="text-lg font-bold text-slate-700">{metrics.avgLeadScore}</p>
                </div>
                <div className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-center">
                    <p className="text-[10px] font-bold uppercase text-slate-400">Engagement</p>
                    <p className="text-lg font-bold text-slate-700">{metrics.avgEngagement}%</p>
                </div>
                <div className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-center">
                    <p className="text-[10px] font-bold uppercase text-slate-400">Campaign share</p>
                    <p className="text-lg font-bold text-slate-700">{metrics.campaignPerformancePct}%</p>
                </div>
            </div>
        </details>
    );
}
