'use client';

import React from 'react';
import Link from 'next/link';
import { LuActivity, LuListChecks, LuUserCheck } from 'react-icons/lu';
import type { AutoGeneratedTask } from '@/lib/leadsIntelligenceDecisionHelpers';
import { leadProfileHref } from '@/lib/leadRoutes';
import { LeadsIntelAiPanel, LeadsIntelAiSectionHeader, MetricPill } from '@/components/leads-intelligence/leadsIntelligenceUi';
import { cn } from '@/lib/utils';

const priorityTone = {
    High: 'border-rose-200 bg-rose-50 text-rose-800',
    Medium: 'border-amber-200 bg-amber-50 text-amber-800',
    Low: 'border-slate-200 bg-slate-50 text-slate-700',
};

export function SalesProductivityPanel({
    productivityScore,
    pipelineHealthScore,
    tasks,
}: {
    productivityScore: number;
    pipelineHealthScore: number;
    tasks: AutoGeneratedTask[];
}) {
    return (
        <LeadsIntelAiPanel variant="amber" className="h-full" aria-label="Sales productivity">
            <LeadsIntelAiSectionHeader
                title="Sales productivity & auto tasks"
                subtitle="Less manual CRM work — AI ranks work and generates tasks from pipeline signals."
                variant="amber"
                badge="Reduce manual work"
            />
            <div className="space-y-4 p-4">
                <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                    <MetricPill label="Sales productivity score" value={`${productivityScore}/100`} tone="violet" />
                    <MetricPill label="Pipeline health score" value={`${pipelineHealthScore}/100`} tone="emerald" />
                </div>

                <div>
                    <div className="mb-2 flex items-center gap-2">
                        <LuListChecks size={14} className="text-amber-700" aria-hidden />
                        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-600">Auto-generated tasks</h3>
                    </div>
                    {tasks.length === 0 ? (
                        <p className="text-sm text-slate-500">No tasks for this view. Add leads or relax filters.</p>
                    ) : (
                        <ul className="space-y-2">
                            {tasks.map((t) => (
                                <li key={t.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-slate-100 bg-slate-50/80 px-3 py-2">
                                    <div className="min-w-0">
                                        <Link href={leadProfileHref(t.leadSlug)} className="text-sm font-semibold text-slate-900 hover:underline">
                                            {t.leadName}
                                        </Link>
                                        <p className="text-xs text-slate-600">
                                            {t.task} · due {t.dueLabel}
                                        </p>
                                    </div>
                                    <span className={cn('rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase', priorityTone[t.priority])}>
                                        {t.priority}
                                    </span>
                                </li>
                            ))}
                        </ul>
                    )}
                </div>

                <p className="flex items-start gap-2 rounded-lg border border-amber-100 bg-amber-50/60 px-3 py-2 text-xs text-amber-900">
                    <LuActivity size={14} className="mt-0.5 shrink-0" aria-hidden />
                    Productivity score reflects conversion lift per rep and unresolved follow-up risk — use it in stand-ups, not as a vanity metric.
                </p>
            </div>
        </LeadsIntelAiPanel>
    );
}

export function NextBestLeadCard({ leadName, leadSlug, action, conversionPct }: { leadName: string; leadSlug: string; action: string; conversionPct: number }) {
    if (!leadName) {
        return (
            <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50/80 px-4 py-6 text-center text-sm text-slate-500">
                No prioritized lead in this view.
            </div>
        );
    }
    return (
        <div className="rounded-2xl border border-violet-200/80 bg-gradient-to-br from-violet-50 via-white to-blue-50 p-4 shadow-sm ring-1 ring-violet-100/60">
            <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                    <p className="text-[10px] font-bold uppercase tracking-wider text-violet-700">Next best lead</p>
                    <Link href={leadProfileHref(leadSlug)} className="mt-1 block text-xl font-bold text-slate-900 hover:text-violet-700 hover:underline">
                        {leadName}
                    </Link>
                    <p className="mt-1 text-sm text-slate-600">
                        Recommended: <span className="font-semibold text-slate-800">{action}</span>
                    </p>
                </div>
                <div className="flex items-center gap-2 rounded-xl border border-violet-200 bg-white px-3 py-2">
                    <LuUserCheck className="text-violet-600" size={18} aria-hidden />
                    <div>
                        <p className="text-[10px] font-bold uppercase text-slate-500">Conversion</p>
                        <p className="text-lg font-bold tabular-nums text-violet-900">{conversionPct}%</p>
                    </div>
                </div>
            </div>
            <Link
                href={leadProfileHref(leadSlug)}
                className="mt-3 inline-flex text-sm font-semibold text-violet-700 hover:underline"
            >
                Open lead and execute →
            </Link>
        </div>
    );
}
