import type { Lead } from '@/lib/leadStore';
import { formatLeadCode } from '@/lib/leadStore';

/** Opens a printable HTML report (use browser Print → Save as PDF). */
export function openLeadsPrintReport(leads: Lead[], title: string) {
    if (typeof window === 'undefined') return;
    const w = window.open('', '_blank');
    if (!w) return;
    const rows = leads
        .map(
            (l) =>
                `<tr><td>${esc(formatLeadCode(l.id))}</td><td>${esc(l.name)}</td><td>${esc(l.email)}</td><td>${esc(l.phone)}</td><td>${esc(l.source)}</td><td>${esc(l.project)}</td><td>${esc(l.budgetRange)}</td><td>${esc(l.preferredUnitType)}</td><td>${esc(l.status)}</td><td>${typeof l.leadScore === 'number' ? l.leadScore : '—'}</td></tr>`,
        )
        .join('');
    w.document.write(`<!DOCTYPE html><html><head><title>${esc(title)}</title>
    <style>
      body{font-family:system-ui,sans-serif;padding:24px;color:#0f172a}
      h1{font-size:20px;margin:0 0 16px}
      table{width:100%;border-collapse:collapse;font-size:12px}
      th,td{border:1px solid #e2e8f0;padding:8px;text-align:left}
      th{background:#f8fafc;font-weight:600}
    </style></head><body>
    <h1>${esc(title)}</h1>
    <table><thead><tr><th>Lead ID</th><th>Lead Name</th><th>Email</th><th>Phone Number</th><th>Lead Source</th><th>Project Interest</th><th>Budget Range</th><th>Preferred Unit Type</th><th>Lead Status</th><th>Score</th></tr></thead>
    <tbody>${rows}</tbody></table>
    <p style="margin-top:16px;font-size:11px;color:#64748b">Generated by mySFT · Use Print → Save as PDF</p>
    </body></html>`);
    w.document.close();
    w.focus();
    setTimeout(() => w.print(), 250);
}

function esc(s: string) {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
