import type { Department } from '@/data/mockData';

function escapeCsv(value: string) {
    const s = value ?? '';
    if (/[",\r\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
    return s;
}

export function downloadDepartmentsCsv(departments: Department[], filename = 'departments-export.csv') {
    const headers = [
        'ID',
        'Department Name',
        'Department Code',
        'Business Unit',
        'Department Head',
        'Users Count',
        'Status',
        'Created Date',
    ];
    const rows = departments.map((d) => [
        String(d.id),
        escapeCsv(d.name),
        escapeCsv(d.code),
        escapeCsv(d.businessUnitName),
        escapeCsv(d.departmentHeadName ?? ''),
        String(d.usersCount),
        escapeCsv(d.status),
        escapeCsv(d.createdDate),
    ]);

    const csv = [headers.join(','), ...rows.map((r) => r.join(','))].join('\r\n');
    const blob = new Blob([`\uFEFF${csv}`], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}

export function openDepartmentsPrintReport(departments: Department[], title: string) {
    if (typeof window === 'undefined') return;
    const w = window.open('', '_blank');
    if (!w) return;
    const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const rows = departments
        .map(
            (d) =>
                `<tr><td>${esc(String(d.id))}</td><td>${esc(d.name)}</td><td>${esc(d.code)}</td><td>${esc(d.businessUnitName)}</td><td>${esc(d.departmentHeadName ?? '—')}</td><td>${d.usersCount}</td><td>${esc(d.status)}</td><td>${esc(d.createdDate)}</td></tr>`,
        )
        .join('');
    w.document.write(`<!DOCTYPE html><html><head><title>${esc(title)}</title>
    <style>
      body{font-family:system-ui,sans-serif;padding:24px;color:#0f172a}
      h1{font-size:20px;margin:0 0 16px}
      table{width:100%;border-collapse:collapse;font-size:12px}
      th,td{border:1px solid #e2e8f0;padding:8px;text-align:left}
      th{background:#f8fafc;font-weight:600}
    </style></head><body>
    <h1>${esc(title)}</h1>
    <table><thead><tr><th>ID</th><th>Department</th><th>Code</th><th>Business Unit</th><th>Head</th><th>Users</th><th>Status</th><th>Created</th></tr></thead>
    <tbody>${rows}</tbody></table>
    <p style="margin-top:16px;font-size:11px;color:#64748b">Generated by mySFT · Use Print → Save as PDF</p>
    </body></html>`);
    w.document.close();
    w.focus();
    setTimeout(() => w.print(), 250);
}
