import type { IntelligenceLead, LeadSource } from '@/lib/leadsIntelligenceStore';
import { getLeadDealContext } from '@/lib/leadsIntelligenceDealContext';
import {
    daysSinceActivity,
    formatRevenueLakhs,
    formatTodayActionLine,
    getActionPriorityScore,
    getConversionConfidence,
    getFollowUpPriority,
    getLastActivityDate,
    getLastFollowUpLabel,
    getLeadRevenuePotentialLakhs,
    getRecommendedActionLabel,
    getRevenueImpactMessage,
    getRiskReason,
    getSuggestedFollowUpChannel,
    isLeadLeakage,
    type RecommendedActionLabel,
} from '@/lib/leadsIntelligenceHelpers';

export type LeadsIntelDatePreset = 'all' | 'today' | 'week' | 'month' | 'custom';

export type LeadsIntelFunnelStep = {
    key: string;
    label: string;
    count: number;
    conversionFromPrev: number | null;
};

export type RevenueOpportunityInsight = {
    id: string;
    title: string;
    detail: string;
    impactLakhs: number;
    leadSlug?: string;
};

export type AutoGeneratedTask = {
    id: string;
    leadId: string;
    leadSlug: string;
    leadName: string;
    task: string;
    dueLabel: string;
    priority: 'High' | 'Medium' | 'Low';
};

export type FollowUpPlannerRow = {
    lead: IntelligenceLead;
    suggestedDate: string;
    priority: ReturnType<typeof getFollowUpPriority>;
    channel: ReturnType<typeof getSuggestedFollowUpChannel>;
    reason: string;
};

function activePipeline(leads: IntelligenceLead[]): IntelligenceLead[] {
    return leads.filter((l) => l.status !== 'Converted' && l.status !== 'Lost');
}

function addDays(iso: string, days: number): string {
    const d = new Date(iso);
    d.setDate(d.getDate() + days);
    return d.toISOString().slice(0, 10);
}

export function dateRangeForLeadsIntelPreset(preset: Exclude<LeadsIntelDatePreset, 'all' | 'custom'>): { dateFrom: string; dateTo: string } {
    const now = new Date();
    const iso = (d: Date) => d.toISOString().slice(0, 10);
    if (preset === 'today') {
        const t = iso(now);
        return { dateFrom: t, dateTo: t };
    }
    if (preset === 'week') {
        const start = new Date(now);
        start.setDate(now.getDate() - now.getDay());
        const end = new Date(start);
        end.setDate(start.getDate() + 6);
        return { dateFrom: iso(start), dateTo: iso(end) };
    }
    const start = new Date(now.getFullYear(), now.getMonth(), 1);
    const end = new Date(now.getFullYear(), now.getMonth() + 1, 0);
    return { dateFrom: iso(start), dateTo: iso(end) };
}

export function buildLeadsIntelligenceFunnel(leads: IntelligenceLead[]): LeadsIntelFunnelStep[] {
    const total = leads.length;
    const qualified = leads.filter((l) => l.status === 'Qualified' || l.status === 'Converted').length;
    const visits = leads.filter((l) => l.activity.some((a) => a.type === 'Meeting')).length;
    const bookings = leads.filter((l) => l.status === 'Converted').length;

    const pct = (num: number, den: number) => (den > 0 ? Math.round((num / den) * 100) : 0);

    const qualifiedRate = pct(qualified, total);
    const visitRate = qualified > 0 ? pct(visits, qualified) : pct(visits, total);
    const bookingRate = visits > 0 ? pct(bookings, visits) : qualified > 0 ? pct(bookings, qualified) : pct(bookings, total);

    return [
        { key: 'total', label: 'Total Leads', count: total, conversionFromPrev: null },
        { key: 'qualified', label: 'Qualified Leads', count: qualified, conversionFromPrev: qualifiedRate },
        { key: 'visits', label: 'Site Visits', count: visits, conversionFromPrev: visitRate },
        { key: 'bookings', label: 'Bookings', count: bookings, conversionFromPrev: bookingRate },
    ];
}

/** Pipeline health 0–100 from funnel step-through and leakage. */
export function getPipelineHealthScore(leads: IntelligenceLead[]): number {
    const steps = buildLeadsIntelligenceFunnel(leads);
    const rates = steps.map((s) => s.conversionFromPrev).filter((v): v is number => v != null);
    const avgStep = rates.length ? rates.reduce((a, b) => a + b, 0) / rates.length : 0;
    const leakagePenalty = leads.length ? (leads.filter(isLeadLeakage).length / leads.length) * 28 : 0;
    return Math.round(Math.min(98, Math.max(22, avgStep * 0.75 + 18 - leakagePenalty)));
}

export function getPotentialClosuresThisWeek(leads: IntelligenceLead[]): IntelligenceLead[] {
    return [...activePipeline(leads)]
        .filter((l) => l.conversionProbability >= 70 && l.temperature !== 'Cold')
        .sort((a, b) => b.conversionProbability - a.conversionProbability)
        .slice(0, 6);
}

export function getRevenueOpportunityInsights(leads: IntelligenceLead[], limit = 4): RevenueOpportunityInsight[] {
    const insights: RevenueOpportunityInsight[] = [];
    const closers = getPotentialClosuresThisWeek(leads);
    for (const l of closers.slice(0, 2)) {
        insights.push({
            id: `close-${l.id}`,
            title: 'Likely to close this week',
            detail: `${l.name} · ${l.conversionProbability}% booking probability`,
            impactLakhs: getLeadRevenuePotentialLakhs(l),
            leadSlug: l.leadSlug,
        });
    }
    const upsell = [...leads]
        .filter((l) => l.status === 'Converted' && l.leadScore >= 85)
        .slice(0, 1);
    for (const l of upsell) {
        insights.push({
            id: `upsell-${l.id}`,
            title: 'Upsell opportunity',
            detail: `Expand unit or parking with ${l.name}`,
            impactLakhs: Math.round(getLeadRevenuePotentialLakhs(l) * 0.35),
            leadSlug: l.leadSlug,
        });
    }
    const cross = [...activePipeline(leads)]
        .filter((l) => l.source === 'Referral' && l.leadScore >= 75)
        .sort((a, b) => b.leadScore - a.leadScore)[0];
    if (cross) {
        insights.push({
            id: `cross-${cross.id}`,
            title: 'Cross-sell — referral network',
            detail: `Introduce ${cross.projectInterest} to referral contacts`,
            impactLakhs: Math.round(getLeadRevenuePotentialLakhs(cross) * 0.25),
            leadSlug: cross.leadSlug,
        });
    }
    const highValue = [...activePipeline(leads)]
        .filter((l) => getLeadRevenuePotentialLakhs(l) >= 40)
        .sort((a, b) => getLeadRevenuePotentialLakhs(b) - getLeadRevenuePotentialLakhs(a))[0];
    if (highValue && insights.length < limit) {
        insights.push({
            id: `hv-${highValue.id}`,
            title: 'High-value opportunity',
            detail: `${highValue.name} · ${formatProject(highValue)}`,
            impactLakhs: getLeadRevenuePotentialLakhs(highValue),
            leadSlug: highValue.leadSlug,
        });
    }
    return insights.slice(0, limit);
}

function formatProject(lead: IntelligenceLead): string {
    return lead.projectInterest && lead.projectInterest !== '—' ? lead.projectInterest : 'General inventory';
}

export function getAiActionCenterRows(leads: IntelligenceLead[], limit = 8): IntelligenceLead[] {
    return [...activePipeline(leads)].sort((a, b) => getActionPriorityScore(b) - getActionPriorityScore(a)).slice(0, limit);
}

export function getFollowUpOpportunityRows(leads: IntelligenceLead[], limit = 6): FollowUpPlannerRow[] {
    const today = new Date().toISOString().slice(0, 10);
    return [...activePipeline(leads)]
        .filter((l) => l.bestCallTimeLabel && l.bestCallTimeLabel !== '—')
        .sort((a, b) => getActionPriorityScore(b) - getActionPriorityScore(a))
        .slice(0, limit)
        .map((lead) => {
            const priority = getFollowUpPriority(lead);
            const daysOut = priority === 'High' ? 0 : priority === 'Medium' ? 1 : 2;
            const last = lead.activity.length ? lead.activity[lead.activity.length - 1].date : lead.createdAt;
            return {
                lead,
                suggestedDate: addDays(last > today ? last : today, daysOut),
                priority,
                channel: getSuggestedFollowUpChannel(lead),
                reason:
                    lead.followUpRisk === 'High'
                        ? 'Overdue follow-up — risk of lead loss'
                        : lead.visitRecommendation
                          ? 'Site visit window — improves booking rate'
                          : 'Planned nurture touchpoint',
            };
        });
}

export function getFollowUpRiskLeads(leads: IntelligenceLead[], limit = 6): IntelligenceLead[] {
    return [...activePipeline(leads)]
        .filter((l) => l.followUpRisk === 'High' || isLeadLeakage(l))
        .sort((a, b) => getActionPriorityScore(b) - getActionPriorityScore(a))
        .slice(0, limit);
}

export function getLeadLeakageAlerts(leads: IntelligenceLead[], limit = 5): IntelligenceLead[] {
    return [...leads].filter(isLeadLeakage).sort((a, b) => a.engagementScore - b.engagementScore).slice(0, limit);
}

export function getNextBestLead(leads: IntelligenceLead[]): IntelligenceLead | null {
    const rows = getAiActionCenterRows(leads, 1);
    return rows[0] ?? null;
}

export function getAutoGeneratedTasks(leads: IntelligenceLead[], limit = 6): AutoGeneratedTask[] {
    const tasks: AutoGeneratedTask[] = [];
    for (const lead of getAiActionCenterRows(leads, limit)) {
        const action = getRecommendedActionLabel(lead);
        let task = 'Call customer';
        if (action === 'Schedule site visit') task = 'Arrange site visit';
        else if (action === 'Send pricing sheet') task = 'Send quotation';
        else if (action === 'Send payment reminder') task = 'Send payment reminder';
        else if (action === 'Escalate to manager') task = 'Escalate to manager';
        else if (action === 'Nurture with content') task = 'Send nurture email';
        tasks.push({
            id: `task-${lead.id}`,
            leadId: lead.id,
            leadSlug: lead.leadSlug,
            leadName: lead.name,
            task,
            dueLabel: lead.bestCallTimeLabel !== '—' ? lead.bestCallTimeLabel : 'Today',
            priority: getFollowUpPriority(lead),
        });
    }
    return tasks;
}

export type AiActionRowMeta = {
    lead: IntelligenceLead;
    action: RecommendedActionLabel;
    confidence: number;
    businessImpact: string;
    revenueImpact: string;
};

export function getAiActionRowsWithMeta(leads: IntelligenceLead[], limit = 8): AiActionRowMeta[] {
    return getAiActionCenterRows(leads, limit).map((lead) => {
        const action = getRecommendedActionLabel(lead);
        return {
            lead,
            action,
            confidence: getConversionConfidence(lead),
            businessImpact:
                lead.conversionProbability >= 75
                    ? 'Accelerates booking this week'
                    : isLeadLeakage(lead)
                      ? 'Stops revenue walking out of pipeline'
                      : 'Clear next step — less manual planning',
            revenueImpact: (() => {
                const deal = getLeadDealContext(lead.leadSlug);
                if (deal?.pendingPaymentLakhs) {
                    return `${getRevenueImpactMessage(lead, action)} · ₹${deal.pendingPaymentLakhs}L pending on booking`;
                }
                return getRevenueImpactMessage(lead, action);
            })(),
        };
    });
}

export type TodaysRevenueAction = {
    id: string;
    lead: IntelligenceLead;
    action: RecommendedActionLabel;
    headline: string;
    potentialRevenueLakhs: number;
    businessImpact: string;
    dealContextHint: string | null;
};

export function getTodaysRevenueActions(leads: IntelligenceLead[], limit = 6): TodaysRevenueAction[] {
    return getAiActionCenterRows(leads, limit).map((lead) => {
        const action = getRecommendedActionLabel(lead);
        return {
            id: `today-${lead.id}`,
            lead,
            action,
            headline: formatTodayActionLine(lead, action),
            potentialRevenueLakhs: getLeadRevenuePotentialLakhs(lead),
            businessImpact: getRevenueImpactMessage(lead, action),
            dealContextHint: getLeadDealContext(lead.leadSlug)?.aiHint ?? null,
        };
    });
}

/** Single problem statement for Priority Actions Center. */
export function getPriorityActionProblem(lead: IntelligenceLead, action: RecommendedActionLabel): string {
    const deal = getLeadDealContext(lead.leadSlug);
    if (deal?.pendingPaymentLakhs) {
        return `₹${deal.pendingPaymentLakhs}L payment pending on booking`;
    }
    const idle = daysSinceActivity(getLastActivityDate(lead));
    if (idle >= 30) return `Lead inactive for ${idle} days`;
    if (lead.visitRecommendation && !lead.activity.some((a) => a.type === 'Meeting')) {
        return 'Site visit pending';
    }
    if (
        (action === 'Send pricing sheet' || lead.nextAction === 'Offer') &&
        !lead.activity.some((a) => a.type === 'Email')
    ) {
        return 'Proposal not sent';
    }
    if (idle >= 7) return `No follow-up for ${idle} days`;
    if (isLeadLeakage(lead)) return getRiskReason(lead);
    if (lead.followUpRisk === 'High') return 'High follow-up risk';
    return getRiskReason(lead);
}

export type PriorityActionRow = {
    id: string;
    lead: IntelligenceLead;
    revenuePotentialLakhs: number;
    problem: string;
    recommendedAction: RecommendedActionLabel;
    businessImpact: string;
};

/** Merged today's actions + AI recommendations — one prioritized list. */
export function getPriorityActionRows(leads: IntelligenceLead[], limit = 8): PriorityActionRow[] {
    return getAiActionRowsWithMeta(leads, limit).map((row) => ({
        id: `priority-${row.lead.id}`,
        lead: row.lead,
        revenuePotentialLakhs: getLeadRevenuePotentialLakhs(row.lead),
        problem: getPriorityActionProblem(row.lead, row.action),
        recommendedAction: row.action,
        businessImpact: row.businessImpact,
    }));
}

export type ExecutiveAttentionSeverity = 'critical' | 'warning';

export type ExecutiveAttentionAlert = {
    id: string;
    severity: ExecutiveAttentionSeverity;
    headline: string;
    detail: string;
    leadSlug?: string;
};

export function getExecutiveAttentionAlerts(
    leads: IntelligenceLead[],
    kpis: { revenueAtRiskLakhs: number },
): ExecutiveAttentionAlert[] {
    const alerts: ExecutiveAttentionAlert[] = [];
    const pipeline = activePipeline(leads);

    if (kpis.revenueAtRiskLakhs >= 15) {
        alerts.push({
            id: 'aggregate-revenue-risk',
            severity: 'critical',
            headline: `₹${kpis.revenueAtRiskLakhs}L opportunity at risk`,
            detail: 'High-risk and leaking leads in this view need manager intervention today.',
        });
    }

    const inactiveLeads = [...pipeline]
        .map((lead) => ({ lead, idle: daysSinceActivity(getLastActivityDate(lead)) }))
        .filter((x) => x.idle >= 14)
        .sort((a, b) => b.idle - a.idle)
        .slice(0, 2);

    for (const { lead, idle } of inactiveLeads) {
        alerts.push({
            id: `inactive-${lead.id}`,
            severity: idle >= 30 ? 'critical' : 'warning',
            headline: `Lead inactive for ${idle} days`,
            detail: `${lead.name} · ${formatRevenueLakhs(getLeadRevenuePotentialLakhs(lead))} opportunity`,
            leadSlug: lead.leadSlug,
        });
    }

    const visitPending = pipeline.filter(
        (l) => l.visitRecommendation && !l.activity.some((a) => a.type === 'Meeting'),
    );
    if (visitPending.length > 0) {
        const names = visitPending
            .slice(0, 3)
            .map((l) => l.name)
            .join(', ');
        alerts.push({
            id: 'site-visit-pending',
            severity: 'warning',
            headline: visitPending.length === 1 ? 'Site visit pending' : `${visitPending.length} site visits pending`,
            detail: names,
            leadSlug: visitPending[0].leadSlug,
        });
    }

    const proposalGap = pipeline.filter(
        (l) =>
            (l.nextAction === 'Offer' || l.conversionProbability >= 68) &&
            !l.activity.some((a) => a.type === 'Email'),
    );
    if (proposalGap.length > 0) {
        alerts.push({
            id: 'proposal-not-sent',
            severity: 'warning',
            headline: 'Proposal not sent',
            detail:
                proposalGap.length === 1
                    ? `${proposalGap[0].name} is in offer stage without proposal logged.`
                    : `${proposalGap[0].name} +${proposalGap.length - 1} more in offer stage without proposal.`,
            leadSlug: proposalGap[0].leadSlug,
        });
    }

    const reps = getSalesTeamPerformance(leads);
    for (const rep of reps.filter((r) => r.followUpCompliancePct < 72 && r.assignedLeads >= 2)) {
        alerts.push({
            id: `rep-followup-${rep.name}`,
            severity: 'warning',
            headline: `${rep.name} has overdue follow-ups`,
            detail: `${rep.followUpCompliancePct}% follow-up compliance on ${rep.assignedLeads} active leads.`,
        });
    }

    const lowRep = [...reps].filter((r) => r.assignedLeads >= 2).sort((a, b) => a.conversionPct - b.conversionPct)[0];
    if (lowRep && lowRep.conversionPct < 58) {
        alerts.push({
            id: `rep-low-conversion-${lowRep.name}`,
            severity: 'critical',
            headline: 'Low conversion salesperson',
            detail: `${lowRep.name} averaging ${lowRep.conversionPct}% conversion — needs coaching or load rebalance.`,
        });
    }

    return alerts.slice(0, 8);
}

export type ExecutiveSummaryPayload = {
    narrative: string;
    focusLine: string;
    stats: { label: string; value: string }[];
};

export function buildExecutiveSummary(
    leads: IntelligenceLead[],
    kpis: {
        forecastRevenueLakhs: number;
        revenueAtRiskLakhs: number;
        hotLeadsRequiringAction: number;
    },
    dealCoverage: { withDeal: number; total: number },
): ExecutiveSummaryPayload {
    const alerts = getExecutiveAttentionAlerts(leads, kpis);
    const criticalCount = alerts.filter((a) => a.severity === 'critical').length;
    const top = getPriorityActionRows(leads, 1)[0];

    return {
        narrative:
            criticalCount > 0
                ? `${criticalCount} critical alert${criticalCount === 1 ? '' : 's'} in this view. Protect ₹${kpis.revenueAtRiskLakhs}L at risk while pushing ₹${kpis.forecastRevenueLakhs}L forecast to close.`
                : `Focus on closing ₹${kpis.forecastRevenueLakhs}L forecast revenue. ${kpis.hotLeadsRequiringAction} hot lead${kpis.hotLeadsRequiringAction === 1 ? '' : 's'} need action today.`,
        focusLine: top
            ? `First move: ${top.recommendedAction} for ${top.lead.name} — ${top.problem}.`
            : 'Adjust filters or add leads to surface executive actions.',
        stats: [
            { label: 'Forecast revenue', value: formatRevenueLakhs(kpis.forecastRevenueLakhs) },
            { label: 'Revenue at risk', value: formatRevenueLakhs(kpis.revenueAtRiskLakhs) },
            { label: 'Hot leads', value: String(kpis.hotLeadsRequiringAction) },
            {
                label: 'Deal-linked leads',
                value: dealCoverage.total ? `${dealCoverage.withDeal}/${dealCoverage.total}` : '—',
            },
        ],
    };
}

export type RevenueAtRiskRow = {
    lead: IntelligenceLead;
    potentialRevenueLakhs: number;
    riskReason: string;
    lastFollowUp: string;
    recommendedAction: RecommendedActionLabel;
};

export function getRevenueAtRiskRows(leads: IntelligenceLead[], limit = 8): RevenueAtRiskRow[] {
    return [...activePipeline(leads)]
        .filter((l) => isLeadLeakage(l) || l.followUpRisk === 'High')
        .sort((a, b) => getLeadRevenuePotentialLakhs(b) - getLeadRevenuePotentialLakhs(a))
        .slice(0, limit)
        .map((lead) => ({
            lead,
            potentialRevenueLakhs: getLeadRevenuePotentialLakhs(lead),
            riskReason: getRiskReason(lead),
            lastFollowUp: getLastFollowUpLabel(lead),
            recommendedAction: getRecommendedActionLabel(lead),
        }));
}

export type LikelyClosureRow = {
    lead: IntelligenceLead;
    conversionProbability: number;
    potentialRevenueLakhs: number;
    expectedCloseDate: string;
};

export function getLikelyClosures(leads: IntelligenceLead[], limit = 8): LikelyClosureRow[] {
    const today = new Date().toISOString().slice(0, 10);
    return [...activePipeline(leads)]
        .filter((l) => l.conversionProbability >= 65)
        .sort((a, b) => b.conversionProbability - a.conversionProbability)
        .slice(0, limit)
        .map((lead) => {
            const daysOut = lead.conversionProbability >= 85 ? 3 : lead.conversionProbability >= 75 ? 7 : 14;
            return {
                lead,
                conversionProbability: lead.conversionProbability,
                potentialRevenueLakhs: getLeadRevenuePotentialLakhs(lead),
                expectedCloseDate: addDays(today, daysOut),
            };
        });
}

export type SalesRepPerformance = {
    name: string;
    assignedLeads: number;
    conversionPct: number;
    revenueClosedLakhs: number;
    followUpCompliancePct: number;
};

export function getSalesTeamPerformance(leads: IntelligenceLead[]): SalesRepPerformance[] {
    const byRep = new Map<
        string,
        { assigned: number; convSum: number; closedRev: number; highRisk: number }
    >();
    for (const l of leads) {
        const key = l.assignedTo.trim() || 'Unassigned';
        const cur = byRep.get(key) ?? { assigned: 0, convSum: 0, closedRev: 0, highRisk: 0 };
        cur.assigned += 1;
        cur.convSum += l.conversionProbability;
        if (l.status === 'Converted') cur.closedRev += getLeadRevenuePotentialLakhs(l);
        if (l.followUpRisk === 'High' && l.status !== 'Converted') cur.highRisk += 1;
        byRep.set(key, cur);
    }
    return [...byRep.entries()]
        .map(([name, r]) => ({
            name,
            assignedLeads: r.assigned,
            conversionPct: Math.round(r.convSum / Math.max(1, r.assigned)),
            revenueClosedLakhs: r.closedRev,
            followUpCompliancePct: Math.round(100 - (r.highRisk / Math.max(1, r.assigned)) * 100),
        }))
        .sort((a, b) => b.conversionPct - a.conversionPct);
}

export type FollowUpRiskCommandRow = {
    lead: IntelligenceLead;
    issueLabel: string;
    potentialRevenueLakhs: number;
    recommendedAction: RecommendedActionLabel;
    quickAction: 'Call Now' | 'Schedule Visit' | 'Assign Owner';
};

export function getFollowUpRiskCommandRows(leads: IntelligenceLead[], limit = 8): FollowUpRiskCommandRow[] {
    return [...activePipeline(leads)]
        .filter((l) => {
            const idle = daysSinceActivity(getLastActivityDate(l));
            return l.followUpRisk === 'High' || idle >= 5 || !l.activity.length;
        })
        .sort((a, b) => getActionPriorityScore(b) - getActionPriorityScore(a))
        .slice(0, limit)
        .map((lead) => {
            const idle = daysSinceActivity(getLastActivityDate(lead));
            const action = getRecommendedActionLabel(lead);
            let issueLabel = 'Missed follow-up';
            if (!lead.activity.length) issueLabel = 'No activity logged';
            else if (idle >= 7) issueLabel = 'Overdue lead';
            let quickAction: FollowUpRiskCommandRow['quickAction'] = 'Call Now';
            if (lead.visitRecommendation || action === 'Schedule site visit') quickAction = 'Schedule Visit';
            else if (!lead.assignedTo.trim()) quickAction = 'Assign Owner';
            return {
                lead,
                issueLabel,
                potentialRevenueLakhs: getLeadRevenuePotentialLakhs(lead),
                recommendedAction: action,
                quickAction,
            };
        });
}

export type SiteVisitConversionStats = {
    siteVisits: number;
    bookings: number;
    conversionPct: number;
};

export function getSiteVisitConversionAnalytics(leads: IntelligenceLead[]): SiteVisitConversionStats {
    const siteVisits = leads.filter((l) => l.activity.some((a) => a.type === 'Meeting')).length;
    const bookings = leads.filter(
        (l) => l.status === 'Converted' && l.activity.some((a) => a.type === 'Meeting'),
    ).length;
    const conversionPct = siteVisits > 0 ? Math.round((bookings / siteVisits) * 100) : 0;
    return { siteVisits, bookings, conversionPct };
}

export type LeadLeakageMonitorSummary = {
    totalAtRisk: number;
    potentialRevenueLossLakhs: number;
    urgentRecoveries: number;
};

export function getLeadLeakageMonitor(leads: IntelligenceLead[]): LeadLeakageMonitorSummary {
    const atRisk = leads.filter(isLeadLeakage);
    return {
        totalAtRisk: atRisk.length,
        potentialRevenueLossLakhs: atRisk.reduce((s, l) => s + getLeadRevenuePotentialLakhs(l), 0),
        urgentRecoveries: atRisk.filter((l) => l.followUpRisk === 'High').length,
    };
}

export function getTopPerformingSource(leads: IntelligenceLead[]): { label: string; conversionPct: number } {
    if (!leads.length) return { label: '—', conversionPct: 0 };
    const bySource = new Map<LeadSource, { sum: number; n: number }>();
    for (const l of leads) {
        const cur = bySource.get(l.source) ?? { sum: 0, n: 0 };
        cur.sum += l.conversionProbability;
        cur.n += 1;
        bySource.set(l.source, cur);
    }
    let bestLabel = leads[0].source;
    let bestAvg = -1;
    for (const [src, { sum, n }] of bySource) {
        const avg = sum / n;
        if (avg > bestAvg) {
            bestAvg = avg;
            bestLabel = src;
        }
    }
    return { label: bestLabel, conversionPct: Math.round(bestAvg) };
}

export function getTopSalesperson(leads: IntelligenceLead[]): { name: string; conversionPct: number } {
    if (!leads.length) return { name: '—', conversionPct: 0 };
    const byRep = new Map<string, { sum: number; n: number }>();
    for (const l of leads) {
        const key = l.assignedTo.trim() || 'Unassigned';
        const cur = byRep.get(key) ?? { sum: 0, n: 0 };
        cur.sum += l.conversionProbability;
        cur.n += 1;
        byRep.set(key, cur);
    }
    let bestName = '';
    let bestAvg = -1;
    for (const [name, { sum, n }] of byRep) {
        const avg = sum / n;
        if (avg > bestAvg) {
            bestAvg = avg;
            bestName = name;
        }
    }
    return { name: bestName, conversionPct: Math.round(bestAvg) };
}

export function getVisitPushRecommendations(leads: IntelligenceLead[], limit = 5): IntelligenceLead[] {
    return [...leads]
        .filter((l) => l.visitRecommendation && l.status !== 'Converted' && l.status !== 'Lost')
        .sort((a, b) => b.leadScore - a.leadScore)
        .slice(0, limit);
}

export function getOptimalFollowUpRows(leads: IntelligenceLead[], limit = 6): IntelligenceLead[] {
    return [...leads]
        .filter((l) => l.bestCallTimeLabel && l.bestCallTimeLabel !== '—')
        .sort((a, b) => b.leadScore - a.leadScore)
        .slice(0, limit);
}
